version: '3'
services:
  postgresql:
    image: postgres:15
    platform: linux/amd64   # for mac silicon chip
    hostname: db
    container_name: oidc-db
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=try-oidc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
